# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from symbolica.core import Expression

@typing.final
class IntegralFamily:
    r"""
    A one-loop integral family: N propagators, their external kinematics, and a
    numerator polynomial in `dot(k, ...)`.
    
    ## Examples
    ```python
    from symbolica import E, S
    from symbolica.community.oneloopreduce import IntegralFamily, Propagator
    
    # A massless bubble with an off-shell external leg and a unit numerator.
    family = IntegralFamily(
        propagators=[Propagator(E("0")), Propagator(E("0"))],
        invariants=[E("s")],
    )
    reduction = family.reduce()
    print(reduction.to_expression())
    
    # A rank-one massless triangle numerator.
    dot, k, q1 = S("oneloopreduce::dot"), S("oneloopreduce::k"), S("oneloopreduce::q1")
    triangle = IntegralFamily(
        propagators=[Propagator(E("0"))] * 3,
        invariants=[E("p1sq"), E("s"), E("p2sq")],
        numerator=dot(k, q1),
    )
    ```
    
    Parameters
    ----------
    propagators : Sequence[Propagator]
        The N loop propagators, in the order that fixes the labelling `r_0 .. r_{N-1}`.
    invariants : Sequence[Expression]
        The `C(N, 2)` pairwise invariants `(r_i - r_j)^2`, in lexicographic `i < j`
        order: `(0,1), (0,2), ..., (0,N-1), (1,2), ...`. A zero entry is treated as
        an on-shell leg and is off-shell regularized internally.
    numerator : Optional[Expression]
        A polynomial in the symmetric linear dot product `oneloopreduce::dot`, built
        from `dot(k, k)` and `dot(k, q_i)`. Defaults to `1` (a scalar integral).
    exponents : Optional[Sequence[int]]
        The power of each propagator. Defaults to `[1] * N`. Must be non-negative
        and sum to at most `oneloopreduce::MAX_TOTAL_INDEX`, which `reduce()`
        enforces.
    
    Raises
    ------
    ValueError
        If `propagators` is empty, or if `invariants` or `exponents` has the wrong
        length for an N-point family.
    """
    @property
    def propagators(self) -> builtins.list[Propagator]:
        r"""
        The propagators of the family.
        """
    @property
    def invariants(self) -> builtins.list[Expression]:
        r"""
        The `C(N, 2)` pairwise invariants, in lexicographic `i < j` order.
        """
    @property
    def numerator(self) -> Expression:
        r"""
        The numerator polynomial.
        """
    @property
    def exponents(self) -> builtins.list[builtins.int]:
        r"""
        The power of each propagator.
        """
    def __new__(cls, propagators: typing.Sequence[Propagator], invariants: typing.Sequence[Expression], numerator: typing.Optional[Expression] = None, exponents: typing.Optional[typing.Sequence[builtins.int]] = None) -> IntegralFamily: ...
    def reduce(self) -> Reduction:
        r"""
        Reduce the family to the scalar masters `A0`, `B0`, `C0` and `D0`.
        
        ## Examples
        ```python
        reduction = family.reduce()
        for coefficient, master in reduction.terms:
            print(master.kind, coefficient)
        ```
        
        Returns
        -------
        Reduction
            The coefficient of each master integral.
        
        Raises
        ------
        ValueError
            If the reduction fails -- on kinematics the reducer cannot handle, or
            on a propagator index that is negative or whose total is beyond the
            depth the recursion can reach. The Rust-side message is included.
        
        Notes
        -----
        The GIL is held for the whole call. Symbolica aborts the process when an
        unlicensed instance is touched from a second thread, so releasing it
        would turn a concurrent call into a crash rather than a speed-up.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MasterIntegral:
    r"""
    One of the four scalar one-loop master integrals.
    
    Instances come out of `Reduction.terms`; there is no public constructor.
    
    ## Examples
    ```python
    _, master = family.reduce().terms[0]
    
    master.kind
    # 'bubble'
    
    master.arguments
    # [s, 0, 0]
    
    master.to_expression()
    # oneloopreduce::B0(s,0,0)
    ```
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        The topology: `'tadpole'`, `'bubble'`, `'triangle'` or `'box'`.
        """
    @property
    def head(self) -> builtins.str:
        r"""
        The head symbol of the master: `'A0'`, `'B0'`, `'C0'` or `'D0'`.
        """
    @property
    def arguments(self) -> builtins.list[Expression]:
        r"""
        The kinematic arguments, in the order the head takes them.
        
        - `A0(m_sq)`
        - `B0(p_sq, m1_sq, m2_sq)`
        - `C0(p1_sq, p2_sq, p12_sq, m1_sq, m2_sq, m3_sq)`
        - `D0(p1_sq, p2_sq, p3_sq, p4_sq, s, t, m1_sq, m2_sq, m3_sq, m4_sq)`
        """
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def to_expression(self) -> Expression:
        r"""
        The master as a Symbolica function call on its head.
        
        ## Examples
        ```python
        master.to_expression()
        # oneloopreduce::C0(p1sq,p2sq,s,0,0,0)
        ```
        
        Returns
        -------
        Expression
            The `A0`/`B0`/`C0`/`D0` head, in the `oneloopreduce` namespace, applied
            to `arguments`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Propagator:
    r"""
    A loop propagator `1 / ((k + r)^2 - mass_sq)`.
    
    Only the mass is carried here. The external offset `r` never enters the
    reduction directly: the reducer works from the pairwise invariants
    `(r_i - r_j)^2` that you hand to `IntegralFamily`.
    
    ## Examples
    ```python
    from symbolica import E
    from symbolica.community.oneloopreduce import Propagator
    
    massless = Propagator(E("0"))
    massive = Propagator(E("mt^2"))
    ```
    
    Parameters
    ----------
    mass_sq : Expression
        The propagator mass squared. Use `E("0")` for a massless line.
    """
    @property
    def mass_sq(self) -> Expression:
        r"""
        The propagator mass squared.
        """
    def __new__(cls, mass_sq: Expression) -> Propagator: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reduction:
    r"""
    The result of reducing an `IntegralFamily`: a linear combination of scalar
    master integrals.
    
    ## Examples
    ```python
    reduction = family.reduce()
    
    len(reduction)
    # 2
    
    for coefficient, master in reduction.terms:
        print(f"{coefficient} * {master.to_expression()}")
    
    reduction.simplify().to_expression()
    ```
    """
    @property
    def terms(self) -> builtins.list[tuple[Expression, MasterIntegral]]:
        r"""
        The `(coefficient, master)` pairs of the reduction.
        """
    def to_expression(self) -> Expression:
        r"""
        Contract the reduction into a single expression over the `A0`/`B0`/`C0`/`D0`
        heads.
        
        ## Examples
        ```python
        family.reduce().to_expression()
        # oneloopreduce::B0(s,0,0)
        ```
        
        Returns
        -------
        Expression
            `sum(coefficient * master.to_expression())` over every term.
        """
    def simplify(self) -> Reduction:
        r"""
        Cancel every coefficient down to lowest terms.
        
        ## Examples
        ```python
        reduction = family.reduce().simplify()
        ```
        
        Returns
        -------
        Reduction
            A new reduction; the receiver is left untouched.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

