# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from symbolica.core import Expression

@typing.final
class IntegralFamily:
    r"""
    A one-loop integral family: N propagators, their external kinematics, and a
    numerator polynomial in `dot(k, ...)`.
    
    ## Examples
    ```python
    from symbolica import E, S
    from symbolica.community.hep.oneloop import IntegralFamily, Propagator
    
    # A massless bubble with an off-shell external leg and a unit numerator.
    family = IntegralFamily(
        propagators=[Propagator(E("0")), Propagator(E("0"))],
        invariants=[E("s")],
    )
    reduction = family.reduce()
    print(reduction.to_expression())
    
    # A rank-one massless triangle numerator.
    dot, k, q1 = S("oneloopreduce::dot"), S("oneloopreduce::k"), S("oneloopreduce::q1")
    triangle = IntegralFamily(
        propagators=[Propagator(E("0"))] * 3,
        invariants=[E("p1sq"), E("s"), E("p2sq")],
        numerator=dot(k, q1),
    )
    ```
    
    Parameters
    ----------
    propagators : Sequence[Propagator]
        The N propagators, in the order that labels `r_0 .. r_{N-1}`.
    invariants : Sequence[Expression]
        The `C(N, 2)` invariants `(r_i - r_j)^2`, in lexicographic order
        `(0,1), (0,2), ..., (1,2), ...`. A zero is an on-shell leg.
    numerator : Optional[Expression]
        A polynomial in `dot(k, k)` and `dot(k, q_i)`, `i < N`, with `k`-free
        coefficients. Defaults to `1`.
    exponents : Optional[Sequence[int]]
        The power of each propagator, non-negative. Defaults to `[1] * N`.
    
    Raises
    ------
    ValueError
        If `propagators` is empty or a list has the wrong length.
    """
    @property
    def propagators(self) -> builtins.list[Propagator]:
        r"""
        The propagators of the family.
        """
    @property
    def invariants(self) -> builtins.list[Expression]:
        r"""
        The `C(N, 2)` pairwise invariants, in lexicographic `i < j` order.
        """
    @property
    def numerator(self) -> Expression:
        r"""
        The numerator polynomial.
        """
    @property
    def exponents(self) -> builtins.list[builtins.int]:
        r"""
        The power of each propagator.
        """
    def __new__(cls, propagators: typing.Sequence[Propagator], invariants: typing.Sequence[Expression], numerator: typing.Optional[Expression] = None, exponents: typing.Optional[typing.Sequence[builtins.int]] = None) -> IntegralFamily: ...
    def reduce(self) -> Reduction:
        r"""
        Reduce the family to the scalar masters `A0`, `B0`, `C0` and `D0`.
        
        ## Examples
        ```python
        reduction = family.reduce()
        for coefficient, master in reduction.terms:
            print(master.kind, coefficient)
        ```
        
        Returns
        -------
        Reduction
            The coefficient of each master integral.
        
        Raises
        ------
        ValueError
            If the numerator, the indices or the kinematics are unsupported, or
            the result would not be finite. The message says which.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MasterIntegral:
    r"""
    One of the four scalar one-loop master integrals.
    
    Instances come out of `Reduction.terms`; there is no public constructor.
    
    ## Examples
    ```python
    _, master = family.reduce().terms[0]
    
    master.kind
    # 'bubble'
    
    master.arguments
    # [s, 0, 0]
    
    master.to_expression()
    # oneloopreduce::B0(s,0,0)
    ```
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        The topology: `'tadpole'`, `'bubble'`, `'triangle'` or `'box'`.
        """
    @property
    def head(self) -> builtins.str:
        r"""
        The head symbol of the master: `'A0'`, `'B0'`, `'C0'` or `'D0'`.
        """
    @property
    def arguments(self) -> builtins.list[Expression]:
        r"""
        The kinematic arguments, in the order the head takes them.
        
        - `A0(m_sq)`
        - `B0(p_sq, m1_sq, m2_sq)`
        - `C0(p1_sq, p2_sq, p12_sq, m1_sq, m2_sq, m3_sq)`
        - `D0(p1_sq, p2_sq, p3_sq, p4_sq, s, t, m1_sq, m2_sq, m3_sq, m4_sq)`
        """
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def to_expression(self) -> Expression:
        r"""
        The master as a Symbolica function call on its head.
        
        ## Examples
        ```python
        master.to_expression()
        # oneloopreduce::C0(p1sq,p2sq,s,0,0,0)
        ```
        
        Returns
        -------
        Expression
            The `A0`/`B0`/`C0`/`D0` head, in the `oneloopreduce` namespace, applied
            to `arguments`.
        """
    def to_oneloopmaster(self, mu_squared: typing.Optional[Expression] = None) -> Expression:
        r"""
        The master as a `oneloopmaster::` call, with the squared scale `mu_squared`
        (default `1`) appended; `master_coefficients` turns it into its Laurent
        coefficients.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Propagator:
    r"""
    A loop propagator `1 / ((k + r)^2 - mass_sq)`. Only the mass is stored; the
    momenta enter through `IntegralFamily`'s invariants.
    
    ## Examples
    ```python
    from symbolica import E
    from symbolica.community.hep.oneloop import Propagator
    
    massless = Propagator(E("0"))
    massive = Propagator(E("mt^2"))
    ```
    
    Parameters
    ----------
    mass_sq : Expression
        The propagator mass squared. Use `E("0")` for a massless line.
    """
    @property
    def mass_sq(self) -> Expression:
        r"""
        The propagator mass squared.
        """
    def __new__(cls, mass_sq: Expression) -> Propagator: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reduction:
    r"""
    The result of reducing an `IntegralFamily`: a linear combination of scalar
    master integrals.
    
    ## Examples
    ```python
    reduction = family.reduce()
    
    len(reduction)
    # 2
    
    for coefficient, master in reduction.terms:
        print(f"{coefficient} * {master.to_expression()}")
    
    reduction.simplify().to_expression()
    ```
    """
    @property
    def terms(self) -> builtins.list[tuple[Expression, MasterIntegral]]:
        r"""
        The `(coefficient, master)` pairs of the reduction.
        """
    def to_expression(self) -> Expression:
        r"""
        The reduction as one expression over the `A0`/`B0`/`C0`/`D0` heads.
        
        ## Examples
        ```python
        family.reduce().to_expression()
        # oneloopreduce::B0(s,0,0)
        ```
        
        Returns
        -------
        Expression
            `sum(coefficient * master.to_expression())` over every term.
        """
    def to_oneloopmaster(self, mu_squared: typing.Optional[Expression] = None) -> Expression:
        r"""
        The reduction over `oneloopmaster::A0..D0` calls, with the squared scale
        `mu_squared` (default `1`) appended. Coefficients keep their exact `d`;
        nothing is expanded in epsilon.
        """
    def simplify(self) -> Reduction:
        r"""
        Cancel every coefficient down to lowest terms.
        
        ## Examples
        ```python
        reduction = family.reduce().simplify()
        ```
        
        Returns
        -------
        Reduction
            A new reduction; the receiver is left untouched.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

